from sprucepy.notifier import Email, get_recipient_emails, get_recipients, get_recipient_attrs
import click
import datetime as dt
from pytz import timezone
from get_data import *

# Filesystem
default_sql_dir = 'queries'
data_dir = 'data'


def _today():
    return dt.date.today()

def _today_pretty():
    return _today().strftime('%a %B %d, %Y')

def _yesterday():
    return dt.date.today() - dt.timedelta(days=1)

def _yesterday_pretty():
    return _yesterday().strftime('%a %B %d, %Y')

def _now():
    return dt.datetime.now().astimezone(timezone('America/New_York'))

def _now_pretty():
    return _now().strftime('%a %B %d, %Y %H:%M %Z')

def _cleanup():
    for f in os.listdir(data_dir):
        if '.csv' in f:
            os.remove(os.path.join(data_dir, f))

@click.command()
@click.argument('query_name')
@click.option('--email_subject', default='Extracted data')
@click.option('--query_directory', default=default_sql_dir)
@click.option('--filename', default='extract')
@click.option('--cleanup/--no-cleanup', default=True)
@click.option('--environ', default='prod')
def main(
    query_name,
    email_subject,
    query_directory,
    filename,
    cleanup,
    environ
):
    task_id = os.environ['TASK_ID']
    run_id = os.environ['RUN_ID']

    # Email subject
    # email_subject = 'Extracted data'

    now = _now_pretty()

    # Email body
    email_body = f'''
    <html>
        <head>
        </head>
        <body>
            <p>Hello,</p>
            <p>
                Here is the data you requested.
                Data was generated <b>{now}</b>.
            </p>
            <p>
                Please email <a href="mailto: jsege@wphospital.org">Jon Sege</a>
                or <a href="mailto: mzelenetz@wphospital.org">Michael Zelenetz</a>
                with any questions.
            </p>
            <div style="width:100%;background-color:#343a40;color:white;padding-left:20px;margin-top:50px">
                <p><i>Generated by WPH Analytics</i></p>
            </div>
        </div>
        </body>
    </html>
    '''

    fp = write_data(query_name, query_directory, query_name.replace('.sql', ''), environ)

    recipients = get_recipients(task_id, 'output')
    emails = get_recipient_emails(recipients)

    e = Email(
        recipients=emails,
        body=email_body,
        from_email='noreply@wphospital.org',
        subject=email_subject,
        body_type='html',
        attachment=fp,
        run=run_id,
        category='output',
        object='task'
    )

    e.build_and_send()

    if cleanup:
        _cleanup()

if __name__ == '__main__':
    main()
