/* All visits with 30-day readmission flag
 * and visit ID of any prior admissions for which
 * this is a readmission
 */
WITH readmissions AS (
	SELECT
		-- ALL VISITS
		  ind.PATIENTID
		, ind.MRN
		, ind.INPATIENTID
		, ind.ADMITTED
		, ind.DISCHARGED
		, ind.DISPOSITIONID
		, l.DISPOSITIONDESC
		, CASE WHEN r.INPATIENTID IS NOT NULL THEN 1 ELSE 0 END AS READMISSION_YN
		, r.INPATIENTID AS READMISSION_FOR
		, ind.ADMITTED - r.DISCHARGED AS DAYS_BETWEEN_VISITS
		, fac.FACILITYDESC AS IndexFacility
	FROM EDM.INPATIENTS ind
	INNER JOIN EDM.LOOKUPFACILITY fac ON fac.FACILITYID = ind.FACILITYID
	LEFT JOIN (
		-- PRIOR ADMISSION
		SELECT
			  prev.PATIENTID
			, prev.INPATIENTID
			, prev.ADMITTED
			, prev.DISCHARGED
		FROM EDM.INPATIENTS prev
		WHERE ADMITPRIORITYID IN (1, 5) --Admit Priority IS urgent OR priority
	) r ON r.PATIENTID = ind.PATIENTID AND ind.ADMITTED - r.DISCHARGED BETWEEN 0 AND 30
	LEFT JOIN EDM.LOOKUPDISPOSITION l ON l.DISPOSITIONID = ind.DISPOSITIONID
	WHERE 1=1
		AND ind.ADMITPRIORITYID IN (1, 5) --Admit Priority IS urgent OR priority
		AND REGEXP_LIKE(fac.FACILITYDESC, '(white plains)|(wph)', 'i')
),

lace_score AS (
	SELECT DISTINCT
		  NATIVEACCTNUMID
		, NUMERICFINDING AS LACE_PLUS
	FROM (
		SELECT
			  NATIVEACCTNUMID
			, FINDINGTYPEID
			, NUMERICFINDING
			, ROW_NUMBER() OVER(PARTITION BY NATIVEACCTNUMID ORDER BY FINDINGDATETIME DESC) AS ROW_RANK
		FROM EDM.FINDINGS_ALL
	)
	WHERE FINDINGTYPEID = 400000040
	AND ROW_RANK = 1
),

clinical_pharm AS (
	select
		hi.PAT_ID
		,hi.PAT_ENC_CSN_ID
		,hi.NOTE_ID
		,NVL(hi.IP_NOTE_TYPE_C, nei.NOTE_TYPE_C) AS Note_Type_C --get either inpatient or outpatient note ID
		,NVL(znti.NAME, znt.NAME) AS Note_Type
		,st.SMARTTEXT_ID
		,st.SMARTTEXT_NAME
		,hi.CRT_INST_LOCAL_DTTM AS Note_Created_Dttm
		, nei.UPD_AUT_LOCAL_DTTM AS Note_Last_Updated_Dttm
		, nei.COSIGN_INST_LOCAL_DTTM AS Note_Cosigned_Dttm
		, nei.NOT_FILETM_LOC_DTTM AS Note_Filed_Dttm
		,nei.NOTE_STATUS_C
		, zns.NAME AS Note_Status
		,nei.AUTHOR_USER_ID
		, emp1.NAME AS Author_Name
		, ser1.PROV_TYPE AS Author_Prov_Type
		,nei.COSIGNUSER_ID
		from HNO_INFO@CLRPROD hi
		INNER JOIN NOTE_ENC_INFO@CLRPROD nei
			on nei.NOTE_ID = hi.NOTE_ID
		left join CLARITY_EMP@CLRPROD emp1
			on emp1.USER_ID = nei.AUTHOR_USER_ID
		inner join CLARITY_SER@CLRPROD ser1
			on ser1.PROV_ID = emp1.PROV_ID
		left join ZC_NOTE_TYPE_IP@CLRPROD znti
			on znti.TYPE_IP_C = hi.IP_NOTE_TYPE_C
		left join ZC_NOTE_TYPE@CLRPROD znt
			on znt.NOTE_TYPE_C = nei.NOTE_TYPE_C
		left join ZC_NOTE_STATUS@CLRPROD zns
			on zns.NOTE_STATUS_C = nei.NOTE_STATUS_C
		left join NOTE_SMARTTEXT_IDS@CLRPROD nsi
			on nsi.NOTE_ID = hi.NOTE_ID
		left join SMARTTEXT@CLRPROD st
			on st.SMARTTEXT_ID = nsi.SMARTTEXTS_ID
		INNER JOIN EDM.INPATIENTS i ON i.NATIVEINPATIENTID = hi.PAT_ENC_CSN_ID
		INNER JOIN EDM.LOOKUPFACILITY fac ON fac.FACILITYID = i.FACILITYID AND REGEXP_LIKE(fac.FACILITYDESC, '(wph)|(white plains)', 'i')
		where lower(ser1.PROV_TYPE) IN ('pharmacist', 'pharmacy')
		AND NVL(hi.IP_NOTE_TYPE_C, nei.NOTE_TYPE_C) NOT IN ('Antibiotic Approval', 'Therapy Update Note')

)--,

--pre AS (
--	SELECT
--		  p.PATIENTID
--		, p.MRN
--		, p.*
--		, lugm.*
--		, RXSTATUS.*
--	FROM EDM.PRESCRIPTIONS@EDWPROD p
--	LEFT JOIN EDM.LOOKUPGENERICMEDICATION lugm ON lugm.GENERICMEDICATIONID = p.GENERICMEDICATIONID
--	LEFT JOIN EDM.LOOKUPPRESCRIPTIONSTATUS rxstatus ON RXSTATUS.PRESCRIPTIONSTATUSID = p.PRESCRIPTIONSTATUSID  -- TODO: CHECK - I DON'T HAVE THIS TABLE?
--	WHERE 1=1
--		AND rxstatus.PRESCRIPTIONSTATUSDESC  NOT IN (
--			'Canceled',
--			'Holding for Referral',
--			'Denied Approval',
--			'Suspend',
--			'Discontinued'
--		)
--		--AND p.PRESCRIPTIONCREATEDATETIME  >= TO_DATE('2021-04-13 23:59:00','YYYY-MM-DD HH24:MI:SS')
--		--AND P.PRESCRIPTIONSTOPDATE >= trunc(sysdate)
--		AND p.STOPREASONID IS NULL
--		AND p.ROUTEID IS NOT NULL
--		AND p.ROUTEID <> 24 -- remove misc routes (wipes, etc.)
--		AND p.SOURCESYSTEM = 'EPIC' -- Remove the Rx from before epic
--)

--CREATE TABLE MZELENETZ.Cohort_Cureatr AS
SELECT DISTINCT
	 i.NATIVEACCTNUMID
	, i.NATIVEINPATIENTID
	, p.PATIENTID
	, p.DOB
	,  p.SEX
	, p.RACEID
	, r.RACEDESC
	, p.ETHNICITYID
	, e.ETHNICITYDESC
	, p.PREFERREDLANGUAGEID
	, pl.PREFERREDLANGUAGEDESC
	, i.MRN
	, i.ADMITTED
	, i.DISCHARGED
	, i.DISCHNSID
	, i.LOS
	, icu.ICUDAYS
	, dispo.DISPOSITIONDESC
	, ns.DEPTDESC AS Discharging_Department
--	, TO_DATE(i.DISCHARGED) - TO_DATE(i.ADMITTED) as OPERATIONAL_LOS
	, mrn.MEDITECH_MRN
	, CASE WHEN i.ERVISITID > 0 THEN 'Yes' ELSE 'No' END AS AdmittedThroughED
	, TRUNC(months_between(i.ADMITTED, p.DOB) / 12) AS AdmitAge
	, pay.PAYORDESC AS PrimaryPayor
	, fc.FINANCIALCLASSDESC AS PrimaryFinancialClass
	, pay2.PAYORDESC AS SecondaryPayor
	, fc2.FINANCIALCLASSDESC AS SecondaryFinancialClass
	, CASE WHEN readmit.READMISSION_YN = 1 THEN 1 ELSE 0 END AS READMISSION_YN
	, readmit.DAYS_BETWEEN_VISITS
	, hl.HL_SCORE
	, hl.HL_DESCRIPTION
	, ls.LACE_PLUS
	, prov.PROVIDERDESC AS DischargeProvider
	, prov.PROVIDERID AS DischargeProviderID
	, CASE WHEN cp.PAT_ENC_CSN_ID IS NOT NULL THEN 1 ELSE 0 END AS CLINICAL_PHARMACY_YN
FROM EDM.INPATIENTS i
INNER JOIN EDM.PATIENTS p ON p.PATIENTID = i.PATIENTID
LEFT JOIN EDM.HBACCTHAR h ON h.NATIVEPATENCOUNTERID = i.NATIVEINPATIENTID
LEFT JOIN (
	SELECT epic.IDENTITY_ID AS EPIC_MRN, mt.IDENTITY_ID AS MEDITECH_MRN
	FROM IDENTITY_ID@CLRPROD epic
	INNER JOIN IDENTITY_ID@CLRPROD mt ON mt.PAT_ID = epic.PAT_ID AND epic.IDENTITY_TYPE_ID = 14 AND mt.IDENTITY_TYPE_ID=505
) mrn ON mrn.EPIC_MRN = i.MRN
INNER JOIN EDM.LOOKUPFACILITY fac ON fac.FACILITYID = i.FACILITYID AND REGEXP_LIKE(fac.FACILITYDESC, '(wph)|(white plains)', 'i')
LEFT JOIN EDM.LOOKUPPREFERREDLANGUAGE pl ON pl.PREFERREDLANGUAGEID = p.PREFERREDLANGUAGEID
LEFT JOIN EDM.LOOKUPRACE r ON r.RACEID = p.RACEID
LEFT JOIN EDM.LOOKUPETHNICITY e ON e.ETHNICITYID = p.ETHNICITYID
LEFT JOIN EDM.LOOKUPDISPOSITION dispo ON dispo.DISPOSITIONID = i.DISPOSITIONID
LEFT JOIN EDM.LOOKUPNURSINGSTATION ns ON ns.NURSINGSTATIONID = i.DISCHNSID
LEFT JOIN EDM.LOOKUPPAYOR pay ON pay.PAYORID = h.HBACCTPRIMPAYORID
LEFT JOIN EDM.LOOKUPFINANCIALCLASS fc ON fc.FINANCIALCLASSID = pay.FINANCIALCLASSID
LEFT JOIN EDM.LOOKUPPAYOR pay2 ON pay2.PAYORID = h.HBACCTSECONDPAYORID
LEFT JOIN EDM.LOOKUPFINANCIALCLASS fc2 ON fc2.FINANCIALCLASSID = pay2.FINANCIALCLASSID
LEFT JOIN (
		SELECT INPATIENTID, count(*) AS ICUDays FROM EDM.INPATIENTSCENSUS c
		INNER JOIN EDM.LOOKUPNURSINGSTATION ns ON ns.NURSINGSTATIONID = c.NURSINGSTATIONID
		WHERE ns.DEPTDESC IN ('WPH CCU', 'WPH ICU')
		GROUP BY INPATIENTID
		) icu ON icu.INPATIENTID = i.INPATIENTID
LEFT JOIN readmissions readmit ON readmit.READMISSION_FOR = i.INPATIENTID
LEFT JOIN (
	SELECT fa.NATIVEENCOUNTERID, fa.NUMERICFINDING AS HL_Score, hli.NATIVEFINDING AS HL_Description
	FROM EDM.FINDINGS_ALL fa
	LEFT JOIN EDM.FINDINGS_ALL hli ON hli.NATIVEENCOUNTERID = fa.NATIVEENCOUNTERID AND hli.FINDINGTYPEID = 400000548
	WHERE fa.FINDINGTYPEID = 400000547
) hl ON hl.NATIVEENCOUNTERID = i.NATIVEINPATIENTID
LEFT JOIN EDM.LOOKUPPROVIDER prov ON prov.PROVIDERID = i.DISCHATTENDID
LEFT JOIN clinical_pharm cp ON cp.PAT_ENC_CSN_ID = i.NATIVEINPATIENTID
LEFT JOIN lace_score ls ON ls.NATIVEACCTNUMID = i.NATIVEACCTNUMID


--SELECT * FROM pre WHERE pre.PATIENTID IN (SELECT PATIENTID FROM COHORT)
