-- Doppler/ultrasound
-- Cancer on problem list (active)
-- VTE?
-- Poor ambulation (flow sheet BMAT score)

WITH dopplers AS (
	SELECT
		  PAT_MRN_ID AS MRN
		, PAT_ID
		, PAT_NAME
		, ss.NAME AS STUDY_STATUS
		, BEGIN_EXAM_DTTM
		, cd.DEPARTMENT_NAME
		, LOC_NAME
		, PROC_NAME
		, IS_CANCELED_YN
		, nt.NOTE_TEXT
		, ORDER_ID
		, ORDERING_CSN_ID
		, PERFORMING_CSN_ID
	FROM V_IMG_STUDY@CLRPROD im
	INNER JOIN CLARITY_DEP@CLRPROD cd ON cd.DEPARTMENT_ID = im.PERFORMING_DEP_ID
	INNER JOIN CLARITY_LOC@CLRPROD cl ON cl.LOC_ID = im.PERFORMING_LOC_ID
	INNER JOIN ORDER_PROC@CLRPROD ord ON ord.ORDER_PROC_ID = im.ORDER_ID
	INNER JOIN PAT_ENC_HSP@CLRPROD enc ON enc.PAT_ENC_CSN_ID = ord.PAT_ENC_CSN_ID
	LEFT JOIN ZC_RADIOLOGY_STS@CLRPROD ss ON ss.RADIOLOGY_STATUS_C = im.STUDY_STATUS_C
	LEFT JOIN HNO_NOTE_TEXT@CLRPROD nt ON nt.NOTE_CSN_ID = im.RESULT_NOTE_CSN
	WHERE 1=1
		AND REGEXP_LIKE(PROC_NAME, 'us duplex lower extremity veins', 'i')
		AND REGEXP_LIKE(LOC_NAME, 'white plains', 'i')
		AND enc.ADT_PAT_CLASS_C IN (101)
)

SELECT
	  dopplers.*
	, CASE WHEN par.PAT_ID IS NOT NULL THEN 1 ELSE 0 END AS CANCER_POPULATION_REGISTRY_YN
FROM dopplers
LEFT JOIN PAT_ACTIVE_REG@CLRPROD par ON par.PAT_ID = dopplers.PAT_ID AND par.REGISTRY_ID = 82030
WHERE BEGIN_EXAM_DTTM BETWEEN TRUNC(SYSDATE) - to_char(sysdate-1, 'd') - 7 AND TRUNC(SYSDATE) - to_char(sysdate, 'd')
