WITH vis AS (
  SELECT
    *
  FROM EDM.INPATIENTS@EDWPROD i
  INNER JOIN JSEGE.INPATIENT_PROVIDER_CLUSTERS clust ON clust.PROVIDERID = i.DISCHATTENDID
),

rea AS (
  SELECT DISTINCT
      vis.INPATIENTID AS INDEXID
    , 1 AS READMISSIONS
  FROM EDM.INPATIENTS@EDWPROD i
  INNER JOIN vis ON vis.PATIENTID = i.PATIENTID
    AND TO_DATE(i.ADMITTED) - TO_DATE(vis.DISCHARGED) BETWEEN 0 AND 30
  WHERE i.ADMITPRIORITYID IN (1, 5)
)

SELECT
    clust.*
  , prov.PROVIDERDESC
  , 1 AS DISCHARGES
  , LOS
  , COALESCE(READMISSIONS, 0) AS READMISSIONS
FROM vis
INNER JOIN JSEGE.INPATIENT_PROVIDER_CLUSTERS clust ON clust.PROVIDERID = vis.DISCHATTENDID
LEFT JOIN rea ON rea.INDEXID = vis.INPATIENTID
INNER JOIN EDM.LOOKUPPROVIDER@EDWPROD prov ON prov.PROVIDERID = clust.PROVIDERID
